/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: calc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "calc.pb-c.h"
void   calculation__init
                     (Calculation         *message)
{
  static Calculation init_value = CALCULATION__INIT;
  *message = init_value;
}
size_t calculation__get_packed_size
                     (const Calculation *message)
{
  assert(message->base.descriptor == &calculation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t calculation__pack
                     (const Calculation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &calculation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t calculation__pack_to_buffer
                     (const Calculation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &calculation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Calculation *
       calculation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Calculation *)
     protobuf_c_message_unpack (&calculation__descriptor,
                                allocator, len, data);
}
void   calculation__free_unpacked
                     (Calculation *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &calculation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const protobuf_c_boolean calculation__monitor__default_value = 0;
static const ProtobufCFieldDescriptor calculation__field_descriptors[12] =
{
  {
    "l_op",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Calculation, has_l_op),
    offsetof(Calculation, l_op),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_op",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Calculation, has_r_op),
    offsetof(Calculation, r_op),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oper",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Calculation, oper),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Calculation, log),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "answer",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Calculation, has_answer),
    offsetof(Calculation, answer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Calculation, has_pr_id),
    offsetof(Calculation, pr_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dq_cl_name",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Calculation, dq_cl_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connected",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Calculation, has_connected),
    offsetof(Calculation, connected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disconnected",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Calculation, has_disconnected),
    offsetof(Calculation, disconnected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_message",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Calculation, other_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monitor",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Calculation, has_monitor),
    offsetof(Calculation, monitor),
    NULL,
    &calculation__monitor__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sem_name",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Calculation, sem_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned calculation__field_indices_by_name[] = {
  4,   /* field[4] = answer */
  7,   /* field[7] = connected */
  8,   /* field[8] = disconnected */
  6,   /* field[6] = dq_cl_name */
  0,   /* field[0] = l_op */
  3,   /* field[3] = log */
  10,   /* field[10] = monitor */
  2,   /* field[2] = oper */
  9,   /* field[9] = other_message */
  5,   /* field[5] = pr_id */
  1,   /* field[1] = r_op */
  11,   /* field[11] = sem_name */
};
static const ProtobufCIntRange calculation__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor calculation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "calculation",
  "Calculation",
  "Calculation",
  "",
  sizeof(Calculation),
  12,
  calculation__field_descriptors,
  calculation__field_indices_by_name,
  2,  calculation__number_ranges,
  (ProtobufCMessageInit) calculation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
